#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=98
STOP=15
USE_PROCD=1
ATFTPD_BIN="/usr/sbin/atftpd --user root --daemon /tmp/upload/"

start_service()
{
	touch /etc/keyfile
	[ -f /tmp/upload/bob_cm.cfg ] || {
		mkdir -p /tmp/upload/
		cp -f /etc/bob_cm.cfg /tmp/upload/bob_cm.cfg
		chmod 777 -R /tmp/upload/
	}
	procd_open_instance
	procd_set_param respawn
	procd_set_param command $ATFTPD_BIN
	procd_close_instance
}